# Makefile for building the fake_mouse_kernel_anti_lock kernel module
# 使用方法: make -f Makefile.kernel_anti_lock

obj-m := fake_mouse_kernel_anti_lock.o

KVERSION := $(shell uname -r)

.PHONY: all clean

all:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) clean
